name = "berkentekin-com"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = "./dist/_worker.js/index.js"
assets = { binding = "ASSETS", directory = "./dist" }

[[d1_databases]]
binding = "berkentekin_db"
database_name = "berkentekin-db"
database_id = "dbfcd6ca-a3e1-4e70-a039-61f93eb326f0"

[[analytics_engine_datasets]]
binding = "berkentekin_analytics"
dataset = "berkentekin-analytics"
